namespace: "alikins"
name: "top_geerlingguy"
version: "0.99.9"
description: "The most powerful collection of roles... IN THE WORLD"
authors: ["Adrian Likins", "Jeff Geerling"]
license:
  - "MIT"
dependencies: {}
